// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ocpyhpbpfvvdafgpkkum.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im9jcHlocGJwZnZ2ZGFmZ3Bra3VtIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTgyMDgyMDcsImV4cCI6MjA3Mzc4NDIwN30.jDLME4MdFi0nGixKuK2TXRCABl6JiBZsuygcQ-gNTrE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});